language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  # - "pypy" - won't work as smmap doesn't work (see smmap/.travis.yml for details)

git:
  # a higher depth is needed for one of the tests - lets fet
  depth: 1000

install:
  - pip install coveralls
  - python -m pip install pip setuptools -U

  - pip install -r requirements.txt

script:
  - ulimit -n 48
  - ulimit -n
  - nosetests -v --with-coverage
  - pip install -e .

after_success:
  - coveralls

