language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    # - "pypy" - won't work as smmap doesn't work (see smmap/.travis.yml for details)

git:
    # a higher depth is needed for one of the tests - lets fet
  depth: 1000

install:
    - pip install coveralls

    - pip install -r requirements.txt

    # Make sure we limit open handles to see if we are leaking them
    - ulimit -n 48
    - ulimit -n

script:
    ## test build &installation
    - python setup.py build
    - pip install -e .
    - nosetests -v --with-coverage

after_success:
    - coveralls

